/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    services: Service;
    customers: Customer;
    partners: Partner;
    messages: Message;
    users: User;
    media: Media;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'el') | ('en' | 'el')[];
  globals: {
    shared: Shared;
    home: Home;
    contact: Contact;
    company: Company;
  };
  globalsSelect: {
    shared: SharedSelect<false> | SharedSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    company: CompanySelect<false> | CompanySelect<true>;
  };
  locale: 'en' | 'el';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Primary hero content shown at the top of the product detail page.
   */
  heroSection: {
    /**
     * Short product title used in the hero and admin title field.
     */
    title: string;
    /**
     * Main headline for the product hero section.
     */
    header: string;
    /**
     * Introductory body copy for the product hero section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Service category this product belongs to.
     */
    service: string | Service;
    /**
     * Primary product image displayed in the hero section.
     */
    image?: (string | null) | Media;
    /**
     * Abstract background image displayed behind this product hero.
     */
    background?: (string | null) | Media;
  };
  /**
   * Feature section that highlights key product capabilities.
   */
  featuresSection?: {
    /**
     * List of product features shown in this section.
     */
    features?:
      | {
          /**
           * Feature title shown in the product feature list.
           */
          title: string;
          /**
           * Description explaining this product feature.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          /**
           * Icon identifier used when rendering this feature.
           */
          icon: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section explaining how the product works.
   */
  howItWorksSection: {
    /**
     * Headline for the how-it-works section.
     */
    header: string;
    /**
     * Supporting copy for the how-it-works section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Ordered steps that explain the product workflow.
     */
    steps?:
      | {
          /**
           * Step title shown in the product workflow.
           */
          title: string;
          /**
           * Description explaining this product workflow step.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          /**
           * Optional image displayed with this workflow step.
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section describing technologies associated with this product.
   */
  technologiesSection: {
    /**
     * Headline for the technologies section.
     */
    header: string;
    /**
     * Supporting copy for the technologies section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Detailed introduction for the technologies section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Technology entries displayed for this product.
     */
    technologies?:
      | {
          /**
           * Technology name shown in the technologies list.
           */
          name: string;
          /**
           * Description explaining this technology entry.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section describing the areas of focus for this product.
   */
  focusSection: {
    /**
     * Headline for the product focus section.
     */
    header: string;
    /**
     * Supporting copy for the product focus section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Implementation examples and case study content for this product.
   */
  implementationsSection: {
    /**
     * Headline for the product implementations section.
     */
    header: string;
    /**
     * Supporting copy for the product implementations section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Case study entries displayed in the implementations section.
     */
    caseStudies?:
      | {
          /**
           * Case study title shown in the implementations section.
           */
          title: string;
          /**
           * Case study summary shown in the implementations section.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Internal page title used in the admin and page metadata.
   */
  title: string;
  /**
   * URL slug for this page, without a leading slash.
   */
  slug: string;
  /**
   * Search metadata used by browsers, social previews, and search engines.
   */
  seo: {
    /**
     * SEO title shown in browser tabs and search result previews.
     */
    title: string;
    /**
     * SEO summary shown in search result and social sharing previews.
     */
    description: string;
    /**
     * Optional keywords that describe the page topic.
     */
    keywords?:
      | {
          /**
           * Single SEO keyword or phrase.
           */
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Image used for social sharing previews when this page is shared.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Primary hero content shown at the top of the service detail page.
   */
  heroSection: {
    /**
     * Short service title used in the hero and admin title field.
     */
    title: string;
    /**
     * Main headline for the service hero section.
     */
    header: string;
    /**
     * Introductory body copy for the service hero section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Abstract background image displayed behind this service hero.
     */
    background?: (string | null) | Media;
  };
  /**
   * Feature section that highlights what this service provides.
   */
  featuresSection: {
    /**
     * Headline for the service features section.
     */
    header: string;
    /**
     * List of service features shown in this section.
     */
    features?:
      | {
          /**
           * Feature title shown in the feature list.
           */
          title: string;
          /**
           * Description explaining this service feature.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section describing the delivery approach for this service.
   */
  approachSection: {
    /**
     * Headline for the service approach section.
     */
    header: string;
    /**
     * Supporting copy for the service approach section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Ordered approach steps shown for this service.
     */
    steps?:
      | {
          /**
           * Step title shown in the approach sequence.
           */
          title: string;
          /**
           * Description explaining this approach step.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Section describing the areas of focus for this service.
   */
  focusSection: {
    /**
     * Headline for the service focus section.
     */
    header: string;
    /**
     * Supporting copy for the service focus section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Implementation examples and case study content for this service.
   */
  implementationsSection: {
    /**
     * Headline for the service implementations section.
     */
    header: string;
    /**
     * Supporting copy for the service implementations section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Case study entries displayed in the implementations section.
     */
    caseStudies?:
      | {
          /**
           * Case study title shown in the implementations section.
           */
          title: string;
          /**
           * Case study summary shown in the implementations section.
           */
          description: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Internal page title used in the admin and page metadata.
   */
  title: string;
  /**
   * URL slug for this page, without a leading slash.
   */
  slug: string;
  /**
   * Search metadata used by browsers, social previews, and search engines.
   */
  seo: {
    /**
     * SEO title shown in browser tabs and search result previews.
     */
    title: string;
    /**
     * SEO summary shown in search result and social sharing previews.
     */
    description: string;
    /**
     * Optional keywords that describe the page topic.
     */
    keywords?:
      | {
          /**
           * Single SEO keyword or phrase.
           */
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Image used for social sharing previews when this page is shared.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Accessible alt text describing the uploaded media.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  /**
   * Customer name shown across the site and in admin lists.
   */
  name: string;
  /**
   * Customer logo displayed in customer listings and page sections.
   */
  logo: string | Media;
  /**
   * Customer website URL used for outbound links.
   */
  website: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  /**
   * Partner name shown across the site and in admin lists.
   */
  name: string;
  /**
   * Partner logo displayed in partner listings and page sections.
   */
  logo: string | Media;
  /**
   * Partner website URL used for outbound links.
   */
  website: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted through the contact page form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  phone?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: string;
  /**
   * The user that the API key is associated with.
   */
  user: string | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  products?: {
    /**
     * Allow clients to find products.
     */
    find?: boolean | null;
    /**
     * Allow clients to create products.
     */
    create?: boolean | null;
    /**
     * Allow clients to update products.
     */
    update?: boolean | null;
  };
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
  };
  customers?: {
    /**
     * Allow clients to find customers.
     */
    find?: boolean | null;
    /**
     * Allow clients to create customers.
     */
    create?: boolean | null;
    /**
     * Allow clients to update customers.
     */
    update?: boolean | null;
  };
  partners?: {
    /**
     * Allow clients to find partners.
     */
    find?: boolean | null;
    /**
     * Allow clients to create partners.
     */
    create?: boolean | null;
    /**
     * Allow clients to update partners.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  shared?: {
    /**
     * Allow clients to find shared global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update shared global.
     */
    update?: boolean | null;
  };
  home?: {
    /**
     * Allow clients to find home global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update home global.
     */
    update?: boolean | null;
  };
  contact?: {
    /**
     * Allow clients to find contact global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update contact global.
     */
    update?: boolean | null;
  };
  company?: {
    /**
     * Allow clients to find company global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update company global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: string | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        header?: T;
        description?: T;
        service?: T;
        image?: T;
        background?: T;
      };
  featuresSection?:
    | T
    | {
        features?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  howItWorksSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  technologiesSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
        technologies?:
          | T
          | {
              name?: T;
              description?: T;
              id?: T;
            };
      };
  focusSection?:
    | T
    | {
        header?: T;
        tagline?: T;
      };
  implementationsSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        caseStudies?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        header?: T;
        description?: T;
        background?: T;
      };
  featuresSection?:
    | T
    | {
        header?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  approachSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  focusSection?:
    | T
    | {
        header?: T;
        tagline?: T;
      };
  implementationsSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        caseStudies?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  firstname?: T;
  lastname?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  products?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  customers?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  partners?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  shared?:
    | T
    | {
        find?: T;
        update?: T;
      };
  home?:
    | T
    | {
        find?: T;
        update?: T;
      };
  contact?:
    | T
    | {
        find?: T;
        update?: T;
      };
  company?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared".
 */
export interface Shared {
  id: string;
  /**
   * Primary site logo used in shared navigation and branding.
   */
  logo: string | Media;
  /**
   * Browser favicon used for the site.
   */
  favicon: string | Media;
  /**
   * Default site title used for branding and metadata.
   */
  siteTitle: string;
  /**
   * Shared header navigation shown across the site.
   */
  header?: {
    /**
     * Top-level navigation links shown in the site header.
     */
    links?:
      | {
          /**
           * Navigation label shown in the header.
           */
          label: string;
          /**
           * Mark this header link as the primary navigation action.
           */
          primary?: boolean | null;
          /**
           * Destination path or URL for this header link.
           */
          link?: string | null;
          /**
           * Dropdown or nested navigation links under this header item.
           */
          subLinks?:
            | {
                /**
                 * Text shown for this call-to-action link.
                 */
                label: string;
                /**
                 * Destination path or URL for this call to action.
                 */
                url: string;
                /**
                 * Enable when the destination is a full external URL.
                 */
                absolute?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Shared footer content shown across the site.
   */
  footer: {
    /**
     * Top footer reach-out section with headline, tagline, and CTA.
     */
    top: {
      /**
       * Headline shown in the top footer section.
       */
      header: string;
      /**
       * Supporting tagline shown in the top footer section.
       */
      tagline: string;
      /**
       * Call to action shown in the top footer section.
       */
      cta: {
        /**
         * Text shown for this call-to-action link.
         */
        label: string;
        /**
         * Destination path or URL for this call to action.
         */
        url: string;
        /**
         * Enable when the destination is a full external URL.
         */
        absolute?: boolean | null;
        id?: string | null;
      };
      /**
       * Abstract background image displayed behind the footer reach-out section.
       */
      background?: (string | null) | Media;
    };
    /**
     * Middle footer section with logo and grouped navigation links.
     */
    middle: {
      /**
       * Logo displayed in the middle footer section.
       */
      logo: string | Media;
      /**
       * Grouped footer navigation columns.
       */
      linkGroups?:
        | {
            /**
             * Heading shown above this footer link group.
             */
            label: string;
            /**
             * Links displayed inside this footer group.
             */
            links?:
              | {
                  /**
                   * Text shown for this call-to-action link.
                   */
                  label: string;
                  /**
                   * Destination path or URL for this call to action.
                   */
                  url: string;
                  /**
                   * Enable when the destination is a full external URL.
                   */
                  absolute?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Bottom footer bar with copyright text and legal links.
     */
    bottom: {
      /**
       * Copyright text shown in the bottom footer bar.
       */
      copyright: string;
      /**
       * Legal or utility links shown in the bottom footer bar.
       */
      links?:
        | {
            /**
             * Text shown for this call-to-action link.
             */
            label: string;
            /**
             * Destination path or URL for this call to action.
             */
            url: string;
            /**
             * Enable when the destination is a full external URL.
             */
            absolute?: boolean | null;
            id?: string | null;
          }[]
        | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  /**
   * Primary hero content shown at the top of the home page.
   */
  heroSection: {
    /**
     * Main headline shown in the home page hero.
     */
    header: string;
    /**
     * Short supporting tagline shown in the home page hero.
     */
    tagline: string;
    /**
     * Introductory body copy for the home page hero.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Label shown for the discover mode control in the hero.
     */
    discoverModeLabel: string;
  };
  /**
   * Introductory about section shown on the home page.
   */
  aboutSection: {
    /**
     * Headline for the home page about section.
     */
    header: string;
    /**
     * Supporting copy for the home page about section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Detailed body copy for the home page about section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Call to action shown in the home page about section.
     */
    cta: {
      /**
       * Text shown for this call-to-action link.
       */
      label: string;
      /**
       * Destination path or URL for this call to action.
       */
      url: string;
      /**
       * Enable when the destination is a full external URL.
       */
      absolute?: boolean | null;
      id?: string | null;
    };
  };
  /**
   * Section introducing services on the home page.
   */
  servicesSection: {
    /**
     * Headline for the home page services section.
     */
    header: string;
    /**
     * Supporting copy for the home page services section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Section introducing products on the home page.
   */
  productsSection: {
    /**
     * Headline for the home page products section.
     */
    header: string;
    /**
     * Supporting copy for the home page products section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Section introducing featured partners on the home page.
   */
  partnersSection: {
    /**
     * Headline for the home page partners section.
     */
    header: string;
    /**
     * Supporting copy for the home page partners section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Detailed body copy for the home page partners section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Partners selected for display in this home page section.
     */
    partners?: (string | Partner)[] | null;
  };
  /**
   * Section introducing featured customers on the home page.
   */
  customersSection: {
    /**
     * Headline for the home page customers section.
     */
    header: string;
    /**
     * Supporting copy for the home page customers section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Detailed body copy for the home page customers section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Customers selected for display in this home page section.
     */
    customers?: (string | Customer)[] | null;
  };
  /**
   * Internal page title used in the admin and page metadata.
   */
  title: string;
  /**
   * URL slug for this page, without a leading slash.
   */
  slug: string;
  /**
   * Search metadata used by browsers, social previews, and search engines.
   */
  seo: {
    /**
     * SEO title shown in browser tabs and search result previews.
     */
    title: string;
    /**
     * SEO summary shown in search result and social sharing previews.
     */
    description: string;
    /**
     * Optional keywords that describe the page topic.
     */
    keywords?:
      | {
          /**
           * Single SEO keyword or phrase.
           */
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Image used for social sharing previews when this page is shared.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: string;
  /**
   * Primary hero content shown at the top of the contact page.
   */
  heroSection: {
    /**
     * Main title shown in the contact page hero.
     */
    title: string;
    /**
     * Introductory body copy for the contact page hero.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Abstract background image displayed behind the contact hero.
     */
    background?: (string | null) | Media;
  };
  /**
   * Contact details and social links shown on the contact page.
   */
  contactSection: {
    /**
     * Headline for the contact details section.
     */
    header: string;
    /**
     * Office or mailing address shown on the contact page.
     */
    address: string;
    /**
     * Phone number shown on the contact page.
     */
    phone: string;
    /**
     * Email address shown on the contact page.
     */
    email: string;
    /**
     * Social profile links shown with the contact details.
     */
    social?:
      | {
          /**
           * Text shown for this call-to-action link.
           */
          label: string;
          /**
           * Destination path or URL for this call to action.
           */
          url: string;
          /**
           * Enable when the destination is a full external URL.
           */
          absolute?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Map location shown beside the contact details.
     */
    location: {
      /**
       * Latitude of the map marker, e.g. 38.0660264.
       */
      latitude: number;
      /**
       * Longitude of the map marker, e.g. 23.760824.
       */
      longitude: number;
      /**
       * Initial map zoom level (1 = world, 21 = building). Defaults to 16.
       */
      zoom?: number | null;
      /**
       * Accessible label / title for the map (e.g. "ThinkRIT office in Metamorfosi").
       */
      label?: string | null;
      /**
       * Optional Google Maps URL opened when visitors click "View on Google Maps".
       */
      link?: string | null;
    };
  };
  /**
   * Introductory content and labels for the contact form.
   */
  sendMessageSection: {
    /**
     * Headline shown above the contact form.
     */
    header: string;
    /**
     * Supporting copy shown above the contact form.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Editable labels used by the contact form inputs and submit button.
     */
    formLabels: {
      /**
       * Label for the first name input.
       */
      firstnameLabel: string;
      /**
       * Label for the last name input.
       */
      lastnameLabel: string;
      /**
       * Label for the email input.
       */
      emailLabel: string;
      /**
       * Label for the phone input.
       */
      phoneLabel: string;
      /**
       * Label for the message input.
       */
      messageLabel: string;
      /**
       * Text shown on the contact form submit button.
       */
      submitLabel: string;
    };
  };
  /**
   * Internal page title used in the admin and page metadata.
   */
  title: string;
  /**
   * URL slug for this page, without a leading slash.
   */
  slug: string;
  /**
   * Search metadata used by browsers, social previews, and search engines.
   */
  seo: {
    /**
     * SEO title shown in browser tabs and search result previews.
     */
    title: string;
    /**
     * SEO summary shown in search result and social sharing previews.
     */
    description: string;
    /**
     * Optional keywords that describe the page topic.
     */
    keywords?:
      | {
          /**
           * Single SEO keyword or phrase.
           */
          keyword: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Image used for social sharing previews when this page is shared.
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: string;
  /**
   * Primary hero content shown at the top of the company page.
   */
  heroSection: {
    /**
     * Main title shown in the company page hero.
     */
    title: string;
    /**
     * Introductory body copy for the company page hero.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Abstract background image displayed behind the company hero.
     */
    background?: (string | null) | Media;
  };
  /**
   * About section content shown on the company page.
   */
  aboutSection: {
    /**
     * Headline for the company about section.
     */
    header: string;
    /**
     * Supporting copy for the company about section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Detailed body copy for the company about section.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Founder profiles and introductory content for the company page.
   */
  foundersSection: {
    /**
     * Headline for the founders section.
     */
    header: string;
    /**
     * Supporting copy for the founders section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Founder profiles displayed on the company page.
     */
    founders?:
      | {
          /**
           * Founder name shown on the profile card.
           */
          name: string;
          /**
           * Founder role or title shown on the profile card.
           */
          role: string;
          /**
           * Founder portrait shown on the company page.
           */
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Team member profiles and introductory content for the company page.
   */
  teamSection: {
    /**
     * Headline for the team section.
     */
    header: string;
    /**
     * Supporting copy for the team section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Team member profiles displayed on the company page.
     */
    teamMembers?:
      | {
          /**
           * Team member name shown on the profile card.
           */
          name: string;
          /**
           * Team member role or title shown on the profile card.
           */
          role: string;
          /**
           * Department or practice area shown for this team member.
           */
          department: string;
          /**
           * Team member portrait shown on the company page.
           */
          image: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Manifesto section content shown on the company page.
   */
  manifestoSection: {
    /**
     * Headline for the manifesto section.
     */
    header: string;
    /**
     * Supporting copy for the manifesto section.
     */
    tagline: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shared_select".
 */
export interface SharedSelect<T extends boolean = true> {
  logo?: T;
  favicon?: T;
  siteTitle?: T;
  header?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              primary?: T;
              link?: T;
              subLinks?:
                | T
                | {
                    label?: T;
                    url?: T;
                    absolute?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  footer?:
    | T
    | {
        top?:
          | T
          | {
              header?: T;
              tagline?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    absolute?: T;
                    id?: T;
                  };
              background?: T;
            };
        middle?:
          | T
          | {
              logo?: T;
              linkGroups?:
                | T
                | {
                    label?: T;
                    links?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          absolute?: T;
                          id?: T;
                        };
                    id?: T;
                  };
            };
        bottom?:
          | T
          | {
              copyright?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    absolute?: T;
                    id?: T;
                  };
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
        discoverModeLabel?: T;
      };
  aboutSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
              absolute?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        header?: T;
        tagline?: T;
      };
  productsSection?:
    | T
    | {
        header?: T;
        tagline?: T;
      };
  partnersSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
        partners?: T;
      };
  customersSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
        customers?: T;
      };
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        description?: T;
        background?: T;
      };
  contactSection?:
    | T
    | {
        header?: T;
        address?: T;
        phone?: T;
        email?: T;
        social?:
          | T
          | {
              label?: T;
              url?: T;
              absolute?: T;
              id?: T;
            };
        location?:
          | T
          | {
              latitude?: T;
              longitude?: T;
              zoom?: T;
              label?: T;
              link?: T;
            };
      };
  sendMessageSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        formLabels?:
          | T
          | {
              firstnameLabel?: T;
              lastnameLabel?: T;
              emailLabel?: T;
              phoneLabel?: T;
              messageLabel?: T;
              submitLabel?: T;
            };
      };
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  heroSection?:
    | T
    | {
        title?: T;
        description?: T;
        background?: T;
      };
  aboutSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        description?: T;
      };
  foundersSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        founders?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              id?: T;
            };
      };
  teamSection?:
    | T
    | {
        header?: T;
        tagline?: T;
        teamMembers?:
          | T
          | {
              name?: T;
              role?: T;
              department?: T;
              image?: T;
              id?: T;
            };
      };
  manifestoSection?:
    | T
    | {
        header?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}